title: Trung's Blog
author: GitHub User
email: trungquoc.nguyen@tum.de
description: > # this means to ignore newlines until "baseurl:"
  This blog is mean to be the first step for creating more interesting blogs!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: Trung Nguyen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
